version: '3.8'
services:
  postgres:
    image: postgres:15.2
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: teknoriego
    volumes:
      - ./data/postgres:/var/lib/postgresql/data